// <auto-generated />
using System;
using CrossChallenge.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrossChallenge.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210103082402_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CrossChallenge.Contracts.Models.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<int>("AthleteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ActivityID");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityID = 1,
                            ActivityType = 8,
                            AthleteID = 1,
                            EndTime = new DateTime(2021, 1, 3, 9, 24, 2, 499, DateTimeKind.Local).AddTicks(7815),
                            Name = "Afternoon walk",
                            Score = 50,
                            StartTime = new DateTime(2021, 1, 3, 9, 24, 2, 496, DateTimeKind.Local).AddTicks(6650),
                            Value = 10.0
                        });
                });

            modelBuilder.Entity("CrossChallenge.Contracts.Models.Athlete", b =>
                {
                    b.Property<int>("AthleteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AthleteID");

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            AthleteID = 1,
                            Email = "donald@duck.com",
                            Firstname = "Donald",
                            Gender = 1,
                            Lastname = "Duck"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
